version: "3.8"
services:
  pgadmin:
    container_name: pgadmin
    build: 
      context: .
      dockerfile: Dockerfile.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_LISTEN_PORT=81
    ports:
      - 8181:81
  db:
    container_name: kancelaria_db
    build:
      context: .
      dockerfile: Dockerfile.psql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  glassfish:
    container_name: kancelaria_glassfish
    build:
      context: .
      dockerfile: Dockerfile.glassfish
    environment:
      - POSTGRES_PASSWORD=kancelaria
    ports:
      - 8080:8080
      - 4848:4848
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db", "asadmin", "start-domain",  "--verbose"]